os: windows
language: shell
branches:
  only:
  - master
install:
  - choco install corretto8jdk
  - choco install innosetup
script: powershell -c "refreshenv; Get-ChildItem Env:; ./gradlew travis --max-workers 1"
